spring:
  datasource:
    url: jdbc:mariadb://localhost:7779/challympic?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create
    properties:A
      hibernate:
#        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      #test

server:
  port: 7777
  servlet:
    context-path: /challympic

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace